// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkwoxrkolanrrjuxyfen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrd294cmtvbGFucnJqdXh5ZmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MTc2NTcsImV4cCI6MjA3NTk5MzY1N30.MeL4PczPDtbt_Iu8z986DiAU9Ny7SiAToxGO3wRuNt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});